name: Build boundingbox Applications
on:
  push:
     paths:
      - 'boundingbox/**'
      - '.github/workflows/boundingbox.yml'
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    #Build Boundingbox application
    - name: Build Bounding Box application
      run: |
        export ARCH=armv7hf        
        cd boundingbox
        docker build --build-arg ARCH=${ARCH} --build-arg PKG_ARCH=cortexa9hf-neon-poky-linux-gnueabi --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --tag boundingboxexample:1.0 .
        docker cp $(docker create  boundingboxexample:1.0):/opt/app build
        cd ..
        mkdir -p acap3/examples/boundingbox/build
        cp boundingbox/build/boundingbox_example_1_0_0_armv7hf.eap acap3/examples/boundingbox/build/boundingbox_example_1_0_0_armv7hf.eap
        
        
       #Run functional tests  
    - name: Run functional tests
      run: |
         export WORKSPACE=$(pwd)
         echo $WORKSPACE
         git clone "https://${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASS }}@gittools.se.axis.com/gerrit/a/tests/atf/tart/recap"
         cd recap  
         git fetch ssh://mirzam@gittools.se.axis.com:29418/tests/atf/tart/recap refs/changes/29/583829/2 && git cherry-pick FETCH_HEAD
         git checkout topic/development/recaptest      
         export ATF_PYTHON=python3     
         ATF_INSTALL=yes source /github-runner/github-runner/init/atf_init.sh
         python --version
         
         chmod +x test_starter.sh
         ./test_starter.sh boundingbox
         ls recap/output
   
    # Save functional test report as artifact
    - uses: actions/upload-artifact@master
      with:
        name: Test report 
        path: recap/recap/output/report.xml 
