name: Build container example applications
on:
  push:
    paths:
      - "container-example/**"
      - ".github/workflows/container-example.yml"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build container exampe application
        run: |
          imagetag=container-example:1.0
          docker image rm -f $imagetag
          cd container-example
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag .):/opt/app ./build
