name: Build object detection Applications
on:
  push:
     paths:
      - 'subscribe-to-object-detection/**'
      - '.github/workflows/object-detection.yml'
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
    
    #Build Object Detection application
    - name: Build Object Detection application
      run: |
        cd subscribe-to-object-detection
        docker build --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --tag vod:1.0 .
        docker cp $(docker create vod:1.0):/opt/app ./build
        cd ..
        mkdir -p acap3/examples/subscribe-to-object-detection/build
        cp subscribe-to-object-detection/build/subscribe_to_object_detection_1_0_0_armv7hf.eap acap3/examples/subscribe-to-object-detection/build/subscribe_to_object_detection_1_0_0_armv7hf.eap
        
        
        
       #Run functional tests  
    - name: Run functional tests
      run: |
         export WORKSPACE=$(pwd)
         echo $WORKSPACE
         git clone "https://${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASS }}@gittools.se.axis.com/gerrit/a/tests/atf/tart/recap"
         cd recap  
         git checkout topic/development/recaptest      
         export ATF_PYTHON=python3     
         ATF_INSTALL=yes source /github-runner/github-runner/init/atf_init.sh
         python --version
         
         chmod +x test_starter.sh
         ./test_starter.sh subscribe_to_object_detection
         ls recap/output
   
    # Save functional test report as artifact
    - uses: actions/upload-artifact@master
      with:
        name: Test report 
        path: recap/recap/output/report.xml
