name: Build vdo-opencl-filtering Application
on:
  push:
     paths:
      - 'vdo-opencl-filtering/**'
      - '.github/workflows/vdo-opencl-filtering.yml'
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      #- uses: actions/checkout@master
      # this will enable shellCheck to be performed
      # on every push to the repo.
    #- name: Run ShellCheck
      #uses: ludeeus/action-shellcheck@master
      # If shellCheck complains about unnecessery things, ignore it.
      #env:
        #SHELLCHECK_OPTS: -e SC2153 -e SC2148

    # Build vdo-opencl-filtering application
    - name: Build vdo-opencl-filtering application
      run: |
        cd vdo-opencl-filtering
        docker build --tag axisecp/vdo_cl_filter_demo:1.0 .
        docker cp $(docker create axisecp/vdo_cl_filter_demo:1.0):/opt/app ./build
        cd ..
        mkdir -p acap3/examples/vdo-opencl-filtering/build
        cp vdo-opencl-filtering/build/vdo_cl_filter_demo_1_0_0_armv7hf.eap acap3/examples/vdo-opencl-filtering/build/vdo_cl_filter_demo_1_0_0_armv7hf.eap


    #Run functional tests
    - name: Run functional tests
      run: |
         export WORKSPACE=$(pwd)
         echo $WORKSPACE
         git clone "https://${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASS }}@gittools.se.axis.com/gerrit/a/tests/atf/tart/recap"
         cd recap
         git checkout topic/development/recaptest
         export ATF_PYTHON=python3
         ATF_INSTALL=yes source /github-runner/github-runner/init/atf_init.sh
         python --version

         chmod +x test_starter.sh
         # TODO ./test_starter.sh vdo-opencl-filtering
         ls recap/output

    # Save functional test report as artifact
    - uses: actions/upload-artifact@master
      with:
        name: Test report
        path: recap/recap/output/report.xml
