name: Build vdostream Application
on:
  push:
    paths:
      - "vdostream/**"
      - ".github/workflows/vdostream.yml"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build vdo stream application
        run: |
          imagetag=vdoencodeclient:1.0
          docker image rm -f $imagetag
          cd vdostream
          docker build --no-cache --tag $imagetag .
          docker cp $(docker create $imagetag):/opt/app ./build
          cd ..
          mkdir -p acap3/examples/vdostream/build
          cp vdostream/build/vdoencodeclient_1_0_0_armv7hf.eap acap3/examples/vdostream/build/vdoencodeclient_1_0_0_armv7hf.eap

      - name: Run functional tests
        run: |
          export WORKSPACE=$(pwd)
          echo $WORKSPACE
          git clone "https://${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASS }}@gittools.se.axis.com/gerrit/a/tests/atf/tart/recap"
          cd recap    
          export ATF_PYTHON=python3     
          ATF_INSTALL=yes source /github-runner/github-runner/init/atf_init.sh
          python --version

          chmod +x test_starter.sh
          ./test_starter.sh vdo_stream
          ls recap/output

      # Save functional test report as artifact
      - uses: actions/upload-artifact@master
        with:
          name: Test report
          path: recap/recap/output/report.xml
